---
title: "Fitted PBE parameters exploration"
author: "Dmitry A. Grechka"
date: "July 6, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)


prepareVisData <- function(id,lglk,x,y,bg) {
t <- data.frame(x=x,y=y)

m <- lm(y ~ poly(x,2),data=t)
m_pred <- function(x) {
  predict(m,newdata = data.frame(x=x))
}

return(
  list(df=t,pred=m_pred,bg=bg,lglk_str=paste0('run ',id,' (lglk ',lglk,')'))
);
}

to_km_per_s <- function(v) {return(v/(1000.0 * 60.0 / 10.0**8.0));}

vis5 <- prepareVisData(
  5,
  11654.1,
  c(0,9.09046,20),
  to_km_per_s(c(0.142469,0.423218,0.802131)),
  to_km_per_s(0.244206))

vis2 <- prepareVisData(
  2,
  10962.7,
  c(0,10.1969,20),
  to_km_per_s(c(0.240187,0.288317,0.435995)),
  to_km_per_s(3.29252e-193))

linetype_scale <- c('1'='solid','2'='dashed')
linetype_scale_labels <- c('1'='burst func','2'='background level')
color_scale <- c('5'='red','2'='green','18'='blue')
color_scale_labels <- c('5'=vis5$lglk_str,'2'=vis2$lglk_str,'18'='fit run 18')

a = ggplot()+
  theme_bw()+
  ggtitle("Particle burst velocity as a function of coronal hole area")+
  xlab("coronal holes total area (%)")+
  ylab("particle burst velocity (km/s)")+

  scale_linetype_manual(values= linetype_scale,labels=linetype_scale_labels)+
  scale_color_manual(values= color_scale,labels=color_scale_labels)+
  
  geom_point(data=vis5$df, aes(x=x, y=y,color='5'))+
  stat_function(data=vis5$df,aes(x,linetype='1',color='5'),fun=vis5$pred) +
  geom_hline(aes(yintercept=vis5$bg,linetype='2',color='5')) +
  
  geom_point(data=vis2$df, aes(x=x, y=y,color='2'))+
  stat_function(data=vis2$df,aes(x,linetype='1',color='2'),fun=vis2$pred) +
  geom_hline(aes(yintercept=vis2$bg,linetype='2',color='2'))
  

print(a)
```

Plotting simulations

```{r simulations}
sim1 <- read.csv('ResultData/docker-0.2-seed-6-iter-156.csv')
sim1.sigma <- to_km_per_s(0.0497358)
sim1$lb68 <- sim1$predMean-sim1.sigma
sim1$ub68 <- sim1$predMean+sim1.sigma
sim1q1 <- sim1[sim1$obs_time<=127590,] #first quantile

b <- ggplot() +
    theme_bw()+
    scale_color_manual(values= color_scale,labels=color_scale_labels)+
    scale_fill_manual(values= color_scale,labels=color_scale_labels)+
  
    geom_point(data=sim1q1,aes(x=obs_time,y=obs),shape=1) +
    geom_line(data=sim1q1,aes(x=obs_time,y=predMean,color='5'),lwd=1) +
    geom_ribbon(data=sim1q1,
                aes(x=obs_time,
                    ymin=lb68,
                    ymax=ub68,color='5',fill='5'),
                alpha=.06)
print(b)
```
